# Generated by Django 5.0.3 on 2024-03-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0003_alter_display_ip_alter_display_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField()),
            ],
        ),
    ]
