# Generated by Django 3.2.25 on 2024-03-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0004_speedlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedrecord',
            name='frame_number',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
