# Generated by Django 5.0.3 on 2024-03-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0005_speedrecord_frame_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
