# Generated by Django 5.0.3 on 2024-03-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0006_radar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radar',
            name='port',
        ),
        migrations.AddField(
            model_name='radar',
            name='host_ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
