# Generated by Django 5.0.3 on 2024-03-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0008_triggerpoint_display_camera_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='camera_pass',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='display',
            name='camera_user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
