# Generated by Django 5.0.3 on 2024-03-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0009_display_camera_pass_display_camera_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguredConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
