# Generated by Django 5.0.3 on 2024-03-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0010_configuredconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedrecord',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
