# Generated by Django 3.2.25 on 2024-04-02 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0013_speedrecord_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='speedrecord',
            name='transcation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
